export const ADD_TO_CART = 'ADD_TO_CART'
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE'
export const REMOVE_PRODUCT_IN_CART = 'REMOVE_PRODUCT_IN_CART'
export const UPDATE_PRODUCT_IN_CART = 'UPDATE_PRODUCT_IN_CART'